// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NightWatch.Infrastructure.Persistence;

#nullable disable

namespace NightWatch.Infrastructure.Migrations
{
    [DbContext(typeof(NightWatchDbContext))]
    [Migration("20260531100000_AddAlertContacts")]
    partial class AddAlertContacts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
