// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NightWatch.Infrastructure.Persistence;

#nullable disable

namespace NightWatch.Infrastructure.Migrations
{
    [DbContext(typeof(NightWatchDbContext))]
    [Migration("20260527090316_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NightWatch.Infrastructure.Persistence.Entities.CustomerTenantEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastVerifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LogAnalyticsWorkspaceId")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal?>("MonthlyBudgetLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TeamsWebhookUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("CustomerTenants", (string)null);
                });

            modelBuilder.Entity("NightWatch.Infrastructure.Persistence.Entities.DailySnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AzureHealthScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BusinessImpactEstimateEur")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostEfficiencyScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GovernanceScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReliabilityScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SecurityScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("SnapshotDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("DailySnapshots", (string)null);
                });

            modelBuilder.Entity("NightWatch.Infrastructure.Persistence.Entities.ExecutiveDashboardLayoutEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LayoutJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserObjectId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserObjectId")
                        .IsUnique();

                    b.ToTable("ExecutiveDashboardLayouts", (string)null);
                });

            modelBuilder.Entity("NightWatch.Infrastructure.Persistence.Entities.GlobalOperationsConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiApiKey")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("AiBriefingPrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("AiCompletionTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("AiEndpoint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal>("AiEstimatedCostUsd")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("AiModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("AiPromptTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("AiTarget")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AiUsageMonthKey")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTimeOffset?>("AiUsageUpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DrSettingsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogAnalyticsWorkspaceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TeamsAlertStateJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("TeamsLastReportSentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TeamsSettingsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ScopeKey")
                        .IsUnique();

                    b.ToTable("GlobalOperationsConfig", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
