// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NightWatch.Infrastructure.Persistence;

#nullable disable

namespace NightWatch.Infrastructure.Migrations
{
    [DbContext(typeof(NightWatchDbContext))]
    [Migration("20260529120000_AddMonthlyHealthSnapshots")]
    partial class AddMonthlyHealthSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NightWatch.Infrastructure.Persistence.Entities.AlertThresholdEntity", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("AlertChannel").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                    b.Property<bool>("IsEnabled").HasColumnType("bit");
                    b.Property<string>("MetricType").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                    b.Property<string>("TenantId").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.Property<decimal>("ThresholdValue").HasColumnType("decimal(18,2)");
                    b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("datetimeoffset");
                    b.HasKey("Id");
                    b.HasIndex("TenantId");
                    b.ToTable("AlertThresholds", (string)null);
                });

            modelBuilder.Entity("NightWatch.Infrastructure.Persistence.Entities.AuditLogEntity", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                    b.Property<long>("DurationMs").HasColumnType("bigint");
                    b.Property<string>("HttpMethod").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
                    b.Property<string>("IpAddress").HasMaxLength(64).HasColumnType("nvarchar(64)");
                    b.Property<string>("Path").IsRequired().HasMaxLength(1024).HasColumnType("nvarchar(1024)");
                    b.Property<int>("StatusCode").HasColumnType("int");
                    b.Property<string>("TenantId").HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.Property<DateTimeOffset>("Timestamp").HasColumnType("datetimeoffset");
                    b.Property<string>("UserEmail").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("UserId").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.HasKey("Id");
                    b.HasIndex("Timestamp");
                    b.HasIndex("UserId");
                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("NightWatch.Infrastructure.Persistence.Entities.CustomerTenantEntity", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTimeOffset>("AddedAt").HasColumnType("datetimeoffset");
                    b.Property<string>("DisplayName").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<DateTimeOffset?>("LastVerifiedAt").HasColumnType("datetimeoffset");
                    b.Property<string>("LogAnalyticsWorkspaceId").HasMaxLength(512).HasColumnType("nvarchar(512)");
                    b.Property<decimal?>("MonthlyBudgetLimit").HasColumnType("decimal(18,2)");
                    b.Property<string>("TeamsWebhookUrl").HasMaxLength(2048).HasColumnType("nvarchar(2048)");
                    b.Property<string>("TenantId").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.Property<string>("VisibleDashboardsJson").HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("TenantId").IsUnique();
                    b.ToTable("CustomerTenants", (string)null);
                });

            modelBuilder.Entity("NightWatch.Infrastructure.Persistence.Entities.DailySnapshotEntity", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<decimal>("AzureHealthScore").HasColumnType("decimal(18,2)");
                    b.Property<decimal>("BusinessImpactEstimateEur").HasColumnType("decimal(18,2)");
                    b.Property<decimal>("CostEfficiencyScore").HasColumnType("decimal(18,2)");
                    b.Property<decimal>("GovernanceScore").HasColumnType("decimal(18,2)");
                    b.Property<decimal>("ReliabilityScore").HasColumnType("decimal(18,2)");
                    b.Property<decimal>("SecurityScore").HasColumnType("decimal(18,2)");
                    b.Property<DateTimeOffset>("SnapshotDate").HasColumnType("datetimeoffset");
                    b.Property<string>("TenantId").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.HasKey("Id");
                    b.ToTable("DailySnapshots", (string)null);
                });

            modelBuilder.Entity("NightWatch.Infrastructure.Persistence.Entities.ExecutiveDashboardLayoutEntity", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("LayoutJson").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("TenantId").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnType("datetimeoffset");
                    b.Property<string>("UserObjectId").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.HasKey("Id");
                    b.HasIndex("TenantId", "UserObjectId").IsUnique();
                    b.ToTable("ExecutiveDashboardLayouts", (string)null);
                });

            modelBuilder.Entity("NightWatch.Infrastructure.Persistence.Entities.GlobalOperationsConfigEntity", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("AiApiKey").IsRequired().HasMaxLength(2048).HasColumnType("nvarchar(2048)");
                    b.Property<string>("AiBriefingPrompt").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<long>("AiCompletionTokens").HasColumnType("bigint");
                    b.Property<string>("AiEndpoint").IsRequired().HasMaxLength(512).HasColumnType("nvarchar(512)");
                    b.Property<decimal>("AiEstimatedCostUsd").HasColumnType("decimal(18,6)");
                    b.Property<string>("AiModel").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.Property<long>("AiPromptTokens").HasColumnType("bigint");
                    b.Property<bool>("AiSummaryEnabled").HasColumnType("bit");
                    b.Property<string>("AiTarget").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                    b.Property<string>("AiUsageMonthKey").IsRequired().HasMaxLength(7).HasColumnType("nvarchar(7)");
                    b.Property<DateTimeOffset?>("AiUsageUpdatedAtUtc").HasColumnType("datetimeoffset");
                    b.Property<string>("DrSettingsJson").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("LogAnalyticsWorkspaceId").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("ScopeKey").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                    b.Property<string>("SubscriptionId").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.Property<string>("TeamsAlertStateJson").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTimeOffset?>("TeamsLastReportSentAt").HasColumnType("datetimeoffset");
                    b.Property<string>("TeamsSettingsJson").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnType("datetimeoffset");
                    b.HasKey("Id");
                    b.HasIndex("ScopeKey").IsUnique();
                    b.ToTable("GlobalOperationsConfig", (string)null);
                });

            modelBuilder.Entity("NightWatch.Infrastructure.Persistence.Entities.MonthlyHealthSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<decimal>("AzureHealthScore").HasColumnType("decimal(5,2)");
                    b.Property<decimal>("SecurityPostureScore").HasColumnType("decimal(5,2)");
                    b.Property<decimal>("PerformanceScore").HasColumnType("decimal(5,2)");
                    b.Property<decimal>("CostEfficiencyScore").HasColumnType("decimal(5,2)");
                    b.Property<decimal>("ReliabilityScore").HasColumnType("decimal(5,2)");
                    b.Property<decimal>("GovernanceComplianceScore").HasColumnType("decimal(5,2)");
                    b.Property<int>("ActiveCriticalAlerts").HasColumnType("int");
                    b.Property<decimal>("BackupCoveragePercent").HasColumnType("decimal(5,2)");
                    b.Property<int>("SubscriptionCount").HasColumnType("int");
                    b.Property<string>("TenantId").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.Property<string>("SnapshotMonth").IsRequired().HasMaxLength(7).HasColumnType("nvarchar(7)");
                    b.Property<DateTimeOffset>("CapturedAt").HasColumnType("datetimeoffset");
                    b.HasKey("Id");
                    b.HasIndex(new[] { "TenantId", "SnapshotMonth" }).IsUnique();
                    b.ToTable("MonthlyHealthSnapshots", (string)null);
                });

            modelBuilder.Entity("NightWatch.Infrastructure.Persistence.Entities.ThresholdBreachEntity", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<decimal>("ActualValue").HasColumnType("decimal(18,2)");
                    b.Property<DateTimeOffset>("BreachedAt").HasColumnType("datetimeoffset");
                    b.Property<string>("MetricType").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                    b.Property<DateTimeOffset?>("ResolvedAt").HasColumnType("datetimeoffset");
                    b.Property<string>("TenantId").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.Property<decimal>("ThresholdValue").HasColumnType("decimal(18,2)");
                    b.HasKey("Id");
                    b.HasIndex("TenantId", "MetricType");
                    b.ToTable("ThresholdBreaches", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
