// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NightWatch.Infrastructure.Persistence;

#nullable disable

namespace NightWatch.Infrastructure.Migrations
{
    [DbContext(typeof(NightWatchDbContext))]
    [Migration("20260529140000_AddReportSchedule")]
    partial class AddReportSchedule
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
